### ISSUE TITLE
Feature Request: Customizable areas

### ISSUE THREAD

**Issue by Duatao7055** [tyon2006/whereAmIGoing#1]
Customizable areas would be an area of coordinates, along the x y and z axes. For example, I would be able to set areas in the config files using 3 coordinate points, creating an area that could have a custom name and subtitle, as well as affect the mob difficulty. These areas would show up with a custom title message and subtitle.

**Comment by tyon2006** [comment]
You know, this actually crossed my mind as a feature, but I made use of something else that might work for you. I used biometweaker and worldedit in combination to make a new biome of my custom name, and then set an area with the custom biome using worldedit. Then, configure my mod to include the new custom biome name you made and badda-bing - Same effect.

Unfortunately, I'd have to refactor basically all of my code to implement your exact feature, so I cannot reasonably implement. The work around above should give you really solid results though (I've tested this myself).
