### ISSUE TITLE
Biome display spams in Midnight dimension

### ISSUE THREAD

**Issue by Duatao7055** [tyon2006/whereAmIGoing#2]
In the midnight dimension, the biome display spams and repeats itself while standing in the same biome. Using whereamigoing 1.2.0 and Midnight 0.3.5

**Comment by tyon2006** [comment]
You are super right. It does do that (and it shouldnt lol). I'm not really sure what's going on here, but I'll see what I can do. This interaction only seems to happen in the midnight's dimension, so I might have to code something in for some weird thing they've done?

**Comment by tyon2006** [comment]
I just added an attempt to fix this to the code. Sorry for the delay on this one. I'll try and get a new version posted in the next few days.

**Comment by tyon2006** [comment]
Fixed in version 1.4.2b+

Thanks for being patient!
